#!/bin/sh

case "$1" in
  'create')
    rm -rf fat32.bin
    dd if=/dev/zero of=fat32.bin count=204800 
    /sbin/mkdosfs fat32.bin -s2 -F32
    ;;

  'mount')
    rm -rf fs
    mkdir fs
    user=`id -u`
    group=`id -g`
    sudo mount -o loop,user,uid=$user,gid=$group -tvfat fat32.bin ./fs
    ;;

  'init')
    mkdir -p fs/vfs/app_card/PALM/Programs
    mkdir -p fs/vfs/app_install
    mkdir -p fs/vfs/app_storage
    if [ -f ../../vfs/app_install/Launcher.prc ];
    then
      cp ../../vfs/app_install/Launcher.prc fs/vfs/app_install
    fi
    if [ -f ../../vfs/app_install/BOOT.prc ];
    then
      cp ../../vfs/app_install/BOOT.prc fs/vfs/app_install
    fi
    ;;

  'umount')
    mkdir -p ./fs
    sudo umount ./fs
    rm -rf fs
    ;;

  *)
    echo "usage: $0 create|mount|init|umount"
    ;;
esac

exit 0
