SOURCE=ucarm.c
APPNAME=UnicornArm
APPID=ucAr
APPTYPE=plgi

CUSTOMPFLAGS=-I$(SRC)/libpumpkin/emulation -I$(SRC)/libpumpkin/emulation/arm
EXTRALIBS=-lunicorn

include ../common.mak
include ../commonp.mak
include ../app.mak
