PROGRAM=DateBook2
SOURCE=DateAgenda.c DateAlarm.c Datebook.c DateDay.c DateDB.c DateDisplay.c DateGlobals.c DateMonth.c DatePref.c DateTransfer.c DateWeek.c ToDoDB.c
APPNAME=Date Book2
APPID=Date

include ../common.mak
include ../commonp.mak
include ../app.mak
