void Initmouse(int16_t type, MOUSE *par, void *mousevec);
void *Ssbrk(int16_t count);
int16_t Floprd(void *buf, int32_t filler, int16_t devno, int16_t sectno, int16_t trackno, int16_t sideno, int16_t count);
int16_t Flopwr(void *buf, int32_t filler, int16_t devno, int16_t sectno, int16_t trackno, int16_t sideno, int16_t count);
int16_t Flopfmt(void);
void Dbmsg(int16_t rsrvd, int16_t msg_num, int32_t msg_arg);
void Midiws(int16_t cnt, void *ptr);
void Mfpint(int16_t number, void *vector);
IOREC *Iorec(int16_t dev);
int32_t Rsconf(int16_t baud, int16_t ctr, int16_t ucr, int16_t rsr, int16_t tsr, int16_t scr);
KEYTAB *Keytbl(void *unshift, void *shift, void *capslock);
int32_t Random(void);
void Protobt(void *buf, int32_t serialno, int16_t disktype, int16_t execflag);
int16_t Flopver(void *buf, int32_t filler, int16_t devno, int16_t sectno, int16_t trackno, int16_t sideno, int16_t count);
void Scrdmp(void);
int16_t Cursconf(int16_t func, int16_t rate);
void Settime(uint32_t time);
uint32_t Gettime(void);
void Bioskeys(void);
void Ikbdws(int16_t count, int8_t *ptr);
void Jdisint(int16_t number);
void Jenabint(int16_t number);
int8_t Giaccess(int16_t dat, int16_t regno);
void Offgibit(int16_t bitno);
void Ongibit(void);
void Xbtimer(int16_t timer, int16_t control, int16_t dat, void *vector);
void *Dosound(int8_t *buf);
int16_t Setprt(int16_t config);
int16_t Kbrate(int16_t initial, int16_t repeat);
int16_t Prtblk(PBDEF *par);
void Vsync(void);
void Puntaes(void);
int16_t Floprate(int16_t devno, int16_t newrate);
int16_t DMAread(int32_t sector, int16_t count, void *buffer, int16_t devno);
int16_t DMAwrite(int32_t sector, int16_t count, void *buffer, int16_t devno);
int32_t Bconmap(int16_t devno);
int16_t NVMaccess(int16_t op, int16_t start, int16_t count, int8_t *buffer);
void Metainit(META_INFO_1 *buffer);
int32_t Metaopen(int16_t drive, META_DRVINFO *buffer);
int32_t Metaclose(int16_t drive);
int32_t Metaread(int16_t drive, void *buffer, int32_t blockno, int16_t count);
int32_t Metawrite(int16_t drive, void *buffer, int32_t blockno, int16_t count);
int32_t Metaseek(int16_t drive, int32_t blockno);
int32_t Metastatus(int16_t drive, void *buffer);
int32_t Metaioctl(int16_t drive, int32_t magic, int16_t opcode, void *buffer);
int32_t Metastartaudio(int16_t drive, int16_t flag, uint8_t *bytearray);
int32_t Metastopaudio(int16_t drive);
int32_t Metasetsongtime(int16_t drive, int16_t repeat, int32_t starttime, int32_t endtime);
int32_t Metagettoc(int16_t drive, int16_t flag, CD_TOC_ENTRY *buffer);
int32_t Metadiscinfo(int16_t drive, CD_DISC_INFO *p);
int16_t Blitmode(int16_t mode);
int16_t EsetShift(int16_t shftMode);
int16_t EgetShift(void);
int16_t EsetBank(int16_t bankNum);
int16_t EsetColor(int16_t colorNum, int16_t color);
void EsetPalette(int16_t colorNum, int16_t count, int16_t *palettePtr);
void EgetPalette(int16_t colorNum, int16_t count, int16_t *palettePtr);
int16_t EsetGray(int16_t sw);
int16_t EsetSmear(int16_t sw);
int16_t VsetMode(int16_t mode);
int16_t mon_type(void);
void VsetSync(int16_t flag);
int32_t VgetSize(int16_t mode);
void VsetRGB(int16_t index, int16_t count, int32_t *array);
void VgetRGB(int16_t index, int16_t count, int32_t *array);
int16_t ValidMode(int16_t mode);
void Dsp_DoBlock(int8_t *data_in, int32_t size_in, int8_t *data_out, int32_t size_out);
void Dsp_BlkHandShake(int8_t *data_in, int32_t size_in, int8_t *data_out, int32_t size_out);
void Dsp_BlkUnpacked(int32_t *data_in, int32_t size_in, int32_t *data_out, int32_t size_out);
void Dsp_InStream(int8_t *data_in, int32_t block_size, int32_t num_blocks, int32_t *blocks_done);
void Dsp_OutStream(int8_t *data_out, int32_t block_size, int32_t num_blocks, int32_t *blocks_done);
void Dsp_IOStream(int8_t *data_in, int8_t *data_out, int32_t block_insize, int32_t block_outsize, int32_t num_blocks, int32_t *blocks_done);
void Dsp_RemoveInterrupts(int16_t mask);
int16_t Dsp_GetWordSize(void);
int16_t Dsp_Lock(void);
void Dsp_Unlock(void);
void Dsp_Available(int32_t *xavailable, int32_t *yavailable);
int16_t Dsp_Reserve(int32_t xreserve, int32_t yreserve);
int16_t Dsp_LoadProg(int8_t *file, int16_t ability, int8_t *buffer);
void Dsp_ExecProg(int8_t *codeptr, int32_t codesize, int16_t ability);
void Dsp_ExecBoot(int8_t *codeptr, int32_t codesize, int16_t ability);
int32_t Dsp_LodToBinary(int8_t *file, int8_t *codeptr);
void Dsp_TriggerHC(int16_t vector);
int16_t Dsp_RequestUniqueAbility(void);
int16_t Dsp_GetProgAbility(void);
void Dsp_FlushSubroutines(void);
int16_t Dsp_LoadSubroutine(int8_t *codeptr, int32_t codesize, int16_t ability);
int16_t Dsp_InqSubrAbility(int16_t ability);
int16_t Dsp_RunSubroutine(int16_t handle);
int16_t Dsp_Hf0(int16_t flag);
int16_t Dsp_Hf1(int16_t flag);
int16_t Dsp_Hf2(void);
int16_t Dsp_Hf3(void);
void Dsp_BlkWords(void *data_in, int32_t size_in, void *data_out, int32_t size_out);
void Dsp_BlkBytes(void *data_in, int32_t size_in, void *data_out, int32_t size_out);
int8_t Dsp_HStat(void);
void Dsp_SetVectors(void *receiver, void *transmitter);
void Dsp_MultBlocks(int32_t numsend, int32_t numreceive, DSPBLOCK *sendblocks, DSPBLOCK *receiveblocks);
int32_t locksnd(void);
int32_t unlocksnd(void);
int32_t soundcmd(int16_t mode, int16_t dat);
int32_t setbuffer(int16_t reg, void *begaddr, void *endaddr);
int32_t setmode(int16_t mode);
int32_t settracks(int16_t playtracks, int16_t rectracks);
int32_t setmontracks(int16_t montrack);
int32_t setinterrupt(int16_t src_inter, int16_t cause);
int32_t buffoper(int16_t mode);
int32_t dsptristate(int16_t dspxmit, int16_t dsprec);
int32_t gpio(int16_t mode, int16_t dat);
int32_t devconnect(int16_t src, int16_t dst, int16_t srcclk, int16_t prescale, int16_t protocol);
int16_t sndstatus(int16_t reset);
int32_t buffptr(int32_t *ptr);
void VsetMask(int32_t ormask, int32_t andmask, int16_t overlay);
int32_t CacheCtrl(int16_t OpCode, int16_t Param);
int32_t WdgCtrl(int16_t OpCode);
int32_t Xbios(int16_t command, int16_t device, int32_t param);
int32_t WavePlay(int16_t flags, int32_t rate, int32_t sptr, int32_t slen);
