#!/bin/sh

rm -f \
  AbtShowAbout.c \
  AlmAlarmCallback.c \
  AlmCancelAll.c \
  AlmDisplayAlarm.c \
  AlmEnableNotification.c \
  AlmGetAlarm.c \
  AlmInit.c \
  AlmSetAlarm.c \
  AlmTimeChange.c \
  AttnDoSpecialEffects.c \
  AttnForgetIt.c \
  AttnGetAttention.c \
  AttnGetCounts.c \
  AttnIndicatorEnable.c \
  AttnIndicatorEnabled.c \
  AttnIterate.c \
  AttnListOpen.c \
  AttnUpdate.c \
  BmpBitsSize.c \
  BmpColortableSize.c \
  BmpCompress.c \
  BmpCreateBitmapV3.c \
  BmpCreate.c \
  BmpDelete.c \
  BmpGetBitDepth.c \
  BmpGetBits.c \
  BmpGetColortable.c \
  BmpGetCompressionType.c \
  BmpGetDensity.c \
  BmpGetDimensions.c \
  BmpGetNextBitmapAnyDensity.c \
  BmpGetNextBitmap.c \
  BmpGetSizes.c \
  BmpGetTransparentValue.c \
  BmpGetVersion.c \
  BmpSetDensity.c \
  BmpSetTransparentValue.c \
  BmpSize.c \
  BtLibAddrAToBtd.c \
  BtLibAddrBtdToA.c \
  BtLibCancelInquiry.c \
  BtLibClose.c \
  BtLibDiscoverMultipleDevices.c \
  BtLibDiscoverSingleDevice.c \
  BtLibGetGeneralPreference.c \
  BtLibGetRemoteDeviceName.c \
  BtLibGetSelectedDevices.c \
  BtLibHandleEvent.c \
  BtLibHandleTransportEvent.c \
  BtLibLinkConnect.c \
  BtLibLinkDisconnect.c \
  BtLibLinkGetState.c \
  BtLibLinkSetState.c \
  BtLibOpen.c \
  BtLibPiconetCreate.c \
  BtLibPiconetDestroy.c \
  BtLibPiconetLockInbound.c \
  BtLibPiconetUnlockInbound.c \
  BtLibRegisterManagementNotification.c \
  BtLibSdpCompareUuids.c \
  BtLibSdpGetPsmByUuid.c \
  BtLibSdpGetServerChannelByUuid.c \
  BtLibSdpParseRawDataElement.c \
  BtLibSdpServiceRecordCreate.c \
  BtLibSdpServiceRecordDestroy.c \
  BtLibSdpServiceRecordGetAttribute.c \
  BtLibSdpServiceRecordGetNumListEntries.c \
  BtLibSdpServiceRecordGetNumLists.c \
  BtLibSdpServiceRecordGetRawAttribute.c \
  BtLibSdpServiceRecordGetSizeOfRawAttribute.c \
  BtLibSdpServiceRecordGetStringOrUrlLength.c \
  BtLibSdpServiceRecordMapRemote.c \
  BtLibSdpServiceRecordSetAttribute.c \
  BtLibSdpServiceRecordSetAttributesForSocket.c \
  BtLibSdpServiceRecordSetRawAttribute.c \
  BtLibSdpServiceRecordsGetByServiceClass.c \
  BtLibSdpServiceRecordStartAdvertising.c \
  BtLibSdpServiceRecordStopAdvertising.c \
  BtLibSdpVerifyRawDataElement.c \
  BtLibSecurityFindTrustedDeviceRecord.c \
  BtLibSecurityGetTrustedDeviceRecordInfo.c \
  BtLibSecurityNumTrustedDeviceRecords.c \
  BtLibSecurityRemoveTrustedDeviceRecord.c \
  BtLibServiceClose.c \
  BtLibServiceIndicateSessionStart.c \
  BtLibServiceOpen.c \
  BtLibServicePlaySound.c \
  BtLibSetGeneralPreference.c \
  BtLibSleep.c \
  BtLibSocketAdvanceCredit.c \
  BtLibSocketClose.c \
  BtLibSocketConnect.c \
  BtLibSocketCreate.c \
  BtLibSocketGetInfo.c \
  BtLibSocketListen.c \
  BtLibSocketRespondToConnection.c \
  BtLibSocketSend.c \
  BtLibStartInquiry.c \
  BtLibUnregisterManagementNotification.c \
  BtLibWake.c \
  CategoryCreateList.c \
  CategoryCreateListV10.c \
  CategoryEdit.c \
  CategoryEditV10.c \
  CategoryEditV20.c \
  CategoryFind.c \
  CategoryFreeList.c \
  CategoryFreeListV10.c \
  CategoryGetName.c \
  CategoryGetNext.c \
  CategoryInitialize.c \
  CategorySelect.c \
  CategorySelectV10.c \
  CategorySetName.c \
  CategorySetTriggerLabel.c \
  CategoryTruncateName.c \
  ClipboardAddItem.c \
  ClipboardAppendItem.c \
  ClipboardGetItem.c \
  CncAddProfile.c \
  CncDeleteProfile.c \
  CncGetProfileInfo.c \
  CncGetProfileList.c \
  CncProfileCloseDB.c \
  CncProfileCount.c \
  CncProfileCreate.c \
  CncProfileDelete.c \
  CncProfileGetCurrent.c \
  CncProfileGetIDFromIndex.c \
  CncProfileGetIDFromName.c \
  CncProfileGetIndex.c \
  CncProfileOpenDB.c \
  CncProfileSetCurrent.c \
  CncProfileSettingGet.c \
  CncProfileSettingSet.c \
  CPMLibAddRandomSeed.c \
  CPMLibClose.c \
  CPMLibDecrypt.c \
  CPMLibDecryptFinal.c \
  CPMLibDecryptInit.c \
  CPMLibDecryptUpdate.c \
  CPMLibEncrypt.c \
  CPMLibEncryptFinal.c \
  CPMLibEncryptInit.c \
  CPMLibEncryptUpdate.c \
  CPMLibEnumerateProviders.c \
  CPMLibExportCipherInfo.c \
  CPMLibExportHashInfo.c \
  CPMLibExportKeyInfo.c \
  CPMLibExportVerifyInfo.c \
  CPMLibGenerateKey.c \
  CPMLibGenerateRandomBytes.c \
  CPMLibGetInfo.c \
  CPMLibGetProviderInfo.c \
  CPMLibHash.c \
  CPMLibHashFinal.c \
  CPMLibHashInit.c \
  CPMLibHashUpdate.c \
  CPMLibImportCipherInfo.c \
  CPMLibImportHashInfo.c \
  CPMLibImportKeyInfo.c \
  CPMLibImportVerifyInfo.c \
  CPMLibOpen.c \
  CPMLibReleaseCipherInfo.c \
  CPMLibReleaseHashInfo.c \
  CPMLibReleaseKeyInfo.c \
  CPMLibReleaseVerifyInfo.c \
  CPMLibSetDebugLevel.c \
  CPMLibSetDefaultProvider.c \
  CPMLibSleep.c \
  CPMLibVerify.c \
  CPMLibVerifyFinal.c \
  CPMLibVerifyInit.c \
  CPMLibVerifyUpdate.c \
  CPMLibWake.c \
  Crc16CalcBlock.c \
  CtlDrawControl.c \
  CtlEnabled.c \
  CtlEraseControl.c \
  CtlGetLabel.c \
  CtlGetSliderValues.c \
  CtlGetValue.c \
  CtlHandleEvent.c \
  CtlHideControl.c \
  CtlHitControl.c \
  CtlNewControl.c \
  CtlNewGraphicControl.c \
  CtlNewSliderControl.c \
  CtlSetEnabled.c \
  CtlSetGraphics.c \
  CtlSetLabel.c \
  CtlSetSliderValues.c \
  CtlSetUsable.c \
  CtlSetValue.c \
  CtlShowControl.c \
  CtlValidatePointer.c \
  _d_add.c \
  DateAdjust.c \
  DateDaysToDate.c \
  DateSecondsToDate.c \
  DateTemplateToAscii.c \
  DateToAscii.c \
  DateToDays.c \
  DateToDOWDMFormat.c \
  DayDrawDays.c \
  DayDrawDaySelector.c \
  DayHandleEvent.c \
  DayOfMonth.c \
  DayOfWeek.c \
  DaysInMonth.c \
  DlkControl.c \
  DlkDispatchRequest.c \
  DlkGetSyncInfo.c \
  DlkSetLogEntry.c \
  DlkStartServer.c \
  DmArchiveRecord.c \
  DmAttachRecord.c \
  DmAttachResource.c \
  DmCloseDatabase.c \
  DmCreateDatabase.c \
  DmCreateDatabaseFromImage.c \
  DmDatabaseInfo.c \
  DmDatabaseProtect.c \
  DmDatabaseSize.c \
  DmDeleteCategory.c \
  DmDeleteDatabase.c \
  DmDeleteRecord.c \
  DmDetachRecord.c \
  DmDetachResource.c \
  DmFindDatabase.c \
  DmFindRecordByID.c \
  DmFindResource.c \
  DmFindResourceType.c \
  DmFindSortPosition.c \
  DmFindSortPositionV10.c \
  DmGet1Resource.c \
  DmGetAppInfoID.c \
  DmGetDatabase.c \
  DmGetDatabaseLockState.c \
  DmGetLastErr.c \
  DmGetNextDatabaseByTypeCreator.c \
  DmGetRecord.c \
  DmGetResource.c \
  DmGetResourceIndex.c \
  DmInit.c \
  DmInsertionSort.c \
  DmMoveCategory.c \
  DmMoveRecord.c \
  DmNewHandle.c \
  DmNewRecord.c \
  DmNewResource.c \
  DmNextOpenDatabase.c \
  DmNextOpenResDatabase.c \
  DmNumDatabases.c \
  DmNumRecords.c \
  DmNumRecordsInCategory.c \
  DmNumResources.c \
  DmOpenDatabaseByTypeCreator.c \
  DmOpenDatabase.c \
  DmOpenDatabaseInfo.c \
  DmOpenDBNoOverlay.c \
  DmPositionInCategory.c \
  DmQueryNextInCategory.c \
  DmQueryRecord.c \
  DmQuickSort.c \
  DmRecordInfo.c \
  DmReleaseRecord.c \
  DmReleaseResource.c \
  DmRemoveRecord.c \
  DmRemoveResource.c \
  DmRemoveSecretRecords.c \
  DmResetRecordStates.c \
  DmResizeRecord.c \
  DmResizeResource.c \
  DmResourceInfo.c \
  DmSearchRecord.c \
  DmSearchResource.c \
  DmSeekRecordInCategory.c \
  DmSet.c \
  DmSetDatabaseInfo.c \
  DmSetRecordInfo.c \
  DmSetResourceInfo.c \
  DmStrCopy.c \
  DmWrite.c \
  DmWriteCheck.c \
  ECFixedDiv.c \
  ECFixedMul.c \
  EncDES.c \
  EncDigestMD4.c \
  EncDigestMD5.c \
  ErrAlertCustom.c \
  ErrDisplayFileLineMsg.c \
  ErrExceptionList.c \
  ErrLongJump.c \
  ErrSetJump.c \
  ErrThrow.c \
  EvtAddEventToQueue.c \
  EvtAddUniqueEventToQueue.c \
  EvtCopyEvent.c \
  EvtDequeueKeyEvent.c \
  EvtDequeuePenPoint.c \
  EvtDequeuePenStrokeInfo.c \
  EvtEnableGraffiti.c \
  EvtEnqueueKey.c \
  EvtEnqueuePenPoint.c \
  EvtEventAvail.c \
  EvtFlushKeyQueue.c \
  EvtFlushNextPenStroke.c \
  EvtFlushPenQueue.c \
  EvtGetEvent.c \
  EvtGetPenBtnList.c \
  EvtGetPen.c \
  EvtGetPenNative.c \
  EvtGetSilkscreenAreaList.c \
  EvtGetSysEvent.c \
  EvtKeyQueueEmpty.c \
  EvtKeyQueueSize.c \
  EvtPenQueueSize.c \
  EvtProcessSoftKeyStroke.c \
  EvtResetAutoOffTimer.c \
  EvtSetAutoOffTimer.c \
  EvtSetKeyQueuePtr.c \
  EvtSetNullEventTick.c \
  EvtSetPenQueuePtr.c \
  EvtSysEventAvail.c \
  EvtSysInit.c \
  EvtWakeup.c \
  EvtWakeupWithoutNilEvent.c \
  ExgAccept.c \
  ExgConnect.c \
  ExgControl.c \
  ExgDBRead.c \
  ExgDBWrite.c \
  ExgDisconnect.c \
  ExgDoDialog.c \
  ExgGet.c \
  ExgGetDefaultApplication.c \
  ExgGetRegisteredApplications.c \
  ExgGetRegisteredTypes.c \
  ExgGetTargetApplication.c \
  ExgInit.c \
  ExgLibAccept.c \
  ExgLibClose.c \
  ExgLibConnect.c \
  ExgLibControl.c \
  ExgLibDisconnect.c \
  ExgLibGet.c \
  ExgLibHandleEvent.c \
  ExgLibOpen.c \
  ExgLibPut.c \
  ExgLibReceive.c \
  ExgLibRequest.c \
  ExgLibSend.c \
  ExgLibSleep.c \
  ExgLibWake.c \
  ExgNotifyGoto.c \
  ExgNotifyPreview.c \
  ExgNotifyReceive.c \
  ExgNotifyReceiveV35.c \
  ExgPut.c \
  ExgReceive.c \
  ExgRegisterData.c \
  ExgRegisterDatatype.c \
  ExgRequest.c \
  ExgSend.c \
  ExgSetDefaultApplication.c \
  ExpCardGetSerialPort.c \
  ExpCardInfo.c \
  ExpCardInserted.c \
  ExpCardPresent.c \
  ExpCardRemoved.c \
  ExpInit.c \
  ExpSlotDriverInstall.c \
  ExpSlotDriverRemove.c \
  ExpSlotEnumerate.c \
  ExpSlotLibFind.c \
  ExpSlotRegister.c \
  ExpSlotUnregister.c \
  FileClose.c \
  FileControl.c \
  FileDelete.c \
  FileOpen.c \
  FileReadLow.c \
  FileSeek.c \
  FileTell.c \
  FileTruncate.c \
  FileWrite.c \
  Find.c \
  FindDrawHeader.c \
  FindGetLineBounds.c \
  FindSaveMatch.c \
  FindStrInStr.c \
  FldCalcFieldHeight.c \
  FldCompactText.c \
  FldCopy.c \
  FldCut.c \
  FldDelete.c \
  FldDirty.c \
  FldDrawField.c \
  FldEraseField.c \
  FldFreeMemory.c \
  FldGetAttributes.c \
  FldGetBounds.c \
  FldGetFont.c \
  FldGetInsPtPosition.c \
  FldGetMaxChars.c \
  FldGetNumberOfBlankLines.c \
  FldGetScrollPosition.c \
  FldGetScrollValues.c \
  FldGetSelection.c \
  FldGetTextAllocatedSize.c \
  FldGetTextHandle.c \
  FldGetTextHeight.c \
  FldGetTextLength.c \
  FldGetTextPtr.c \
  FldGetVisibleLines.c \
  FldGrabFocus.c \
  FldHandleEvent.c \
  FldInsert.c \
  FldMakeFullyVisible.c \
  FldNewField.c \
  FldPaste.c \
  FldRecalculateField.c \
  FldReleaseFocus.c \
  FldScrollable.c \
  FldScrollField.c \
  FldSendChangeNotification.c \
  FldSendHeightChangeNotification.c \
  FldSetAttributes.c \
  FldSetBounds.c \
  FldSetDirty.c \
  FldSetFont.c \
  FldSetInsertionPoint.c \
  FldSetInsPtPosition.c \
  FldSetMaxChars.c \
  FldSetMaxVisibleLines.c \
  FldSetScrollPosition.c \
  FldSetSelection.c \
  FldSetTextAllocatedSize.c \
  FldSetText.c \
  FldSetTextHandle.c \
  FldSetTextPtr.c \
  FldSetUsable.c \
  FldUndo.c \
  FldWordWrap.c \
  FlpAToF.c \
  FlpFToA.c \
  FlpVersion.c \
  FntAverageCharWidth.c \
  FntBaseLine.c \
  FntCharHeight.c \
  FntCharsInWidth.c \
  FntCharsWidth.c \
  FntCharWidth.c \
  FntDefineFont.c \
  FntDescenderHeight.c \
  FntGetFont.c \
  FntGetFontPtr.c \
  FntGetScrollValues.c \
  FntLineHeight.c \
  FntLineWidth.c \
  FntSetFont.c \
  FntWCharWidth.c \
  FntWidthToOffset.c \
  FntWordWrap.c \
  FntWordWrapReverseNLines.c \
  FontSelect.c \
  FrmActiveState.c \
  FrmAddSpaceForObject.c \
  FrmAlert.c \
  FrmCloseAllForms.c \
  FrmCopyLabel.c \
  FrmCopyTitle.c \
  FrmCustomAlert.c \
  FrmCustomResponseAlert.c \
  FrmDeleteForm.c \
  FrmDispatchEvent.c \
  FrmDoDialog.c \
  FrmDrawForm.c \
  FrmEraseForm.c \
  FrmGetActiveField.c \
  FrmGetActiveForm.c \
  FrmGetActiveFormID.c \
  FrmGetControlGroupSelection.c \
  FrmGetControlValue.c \
  FrmGetDIAPolicyAttr.c \
  FrmGetFirstForm.c \
  FrmGetFocus.c \
  FrmGetFormBounds.c \
  FrmGetFormId.c \
  FrmGetFormPtr.c \
  FrmGetGadgetData.c \
  FrmGetLabel.c \
  FrmGetNumberOfObjects.c \
  FrmGetObjectBounds.c \
  FrmGetObjectId.c \
  FrmGetObjectIndex.c \
  FrmGetObjectIndexFromPtr.c \
  FrmGetObjectPosition.c \
  FrmGetObjectPtr.c \
  FrmGetObjectType.c \
  FrmGetTitle.c \
  FrmGetUserModifiedState.c \
  FrmGetWindowHandle.c \
  FrmGotoForm.c \
  FrmHandleEvent.c \
  FrmHelp.c \
  FrmHideObject.c \
  FrmInitForm.c \
  FrmNewBitmap.c \
  FrmNewForm.c \
  FrmNewGadget.c \
  FrmNewGsi.c \
  FrmNewLabel.c \
  FrmPointInTitle.c \
  FrmPopupForm.c \
  FrmRemoveObject.c \
  FrmReturnToForm.c \
  FrmSaveAllForms.c \
  FrmSetActiveForm.c \
  FrmSetCategoryLabel.c \
  FrmSetControlGroupSelection.c \
  FrmSetControlValue.c \
  FrmSetDIAPolicyAttr.c \
  FrmSetEventHandler.c \
  FrmSetFocus.c \
  FrmSetGadgetData.c \
  FrmSetGadgetHandler.c \
  FrmSetMenu.c \
  FrmSetNotUserModified.c \
  FrmSetObjectBounds.c \
  FrmSetObjectPosition.c \
  FrmSetTitle.c \
  FrmShowObject.c \
  FrmUpdateForm.c \
  FrmUpdateScrollers.c \
  FrmValidatePtr.c \
  FrmVisible.c \
  FSCustomControl.c \
  FSDirCreate.c \
  FSDirEntryEnumerate.c \
  FSFileClose.c \
  FSFileCreate.c \
  FSFileDelete.c \
  FSFileEOF.c \
  FSFileGetAttributes.c \
  FSFileGetDate.c \
  FSFileOpen.c \
  FSFileRead.c \
  FSFileRename.c \
  FSFileResize.c \
  FSFileSeek.c \
  FSFileSetAttributes.c \
  FSFileSetDate.c \
  FSFileSize.c \
  FSFilesystemType.c \
  FSFileTell.c \
  FSFileWrite.c \
  FSLibAPIVersion.c \
  FSLibClose.c \
  FSLibOpen.c \
  FSLibSleep.c \
  FSLibWake.c \
  FSVolumeFormat.c \
  FSVolumeGetLabel.c \
  FSVolumeInfo.c \
  FSVolumeMount.c \
  FSVolumeSetLabel.c \
  FSVolumeSize.c \
  FSVolumeUnmount.c \
  FtrGetByIndex.c \
  FtrGet.c \
  FtrInit.c \
  FtrPtrFree.c \
  FtrPtrNew.c \
  FtrPtrResize.c \
  FtrSet.c \
  FtrUnregister.c \
  GPDClose.c \
  GPDGetVersion.c \
  GPDOpen.c \
  GPDReadInstant.c \
  GPSClose.c \
  GPSGetLibAPIVersion.c \
  GPSGetMaxSatellites.c \
  GPSGetPosition.c \
  GPSGetPVT.c \
  GPSGetSatellites.c \
  GPSGetStatus.c \
  GPSGetTime.c \
  GPSGetVelocity.c \
  GPSOpen.c \
  GrfAddMacro.c \
  GrfAddPoint.c \
  GrfBeginStroke.c \
  GrfCleanState.c \
  GrfDeleteMacro.c \
  GrfFieldChange.c \
  GrfFilterPoints.c \
  GrfFindBranch.c \
  GrfFlushPoints.c \
  GrfFree.c \
  GrfGetAndExpandMacro.c \
  GrfGetGlyphMapping.c \
  GrfGetMacro.c \
  GrfGetMacroName.c \
  GrfGetNumPoints.c \
  GrfGetPoint.c \
  GrfGetState.c \
  GrfInit.c \
  GrfInitState.c \
  GrfMatch.c \
  GrfMatchGlyph.c \
  GrfProcessStroke.c \
  GrfSetState.c \
  GsiEnable.c \
  GsiEnabled.c \
  GsiInitialize.c \
  GsiSetLocation.c \
  GsiSetShiftState.c \
  HostAscTime.c \
  HostClock.c \
  HostCloseDir.c \
  HostCTime.c \
  HostDbgClearDataBreak.c \
  HostDbgSetDataBreak.c \
  HostErrNo.c \
  HostExgLibAccept.c \
  HostExgLibClose.c \
  HostExgLibConnect.c \
  HostExgLibControl.c \
  HostExgLibDisconnect.c \
  HostExgLibGet.c \
  HostExgLibHandleEvent.c \
  HostExgLibOpen.c \
  HostExgLibPut.c \
  HostExgLibReceive.c \
  HostExgLibRequest.c \
  HostExgLibSend.c \
  HostExgLibSleep.c \
  HostExgLibWake.c \
  HostExportFile.c \
  HostFClose.c \
  HostFEOF.c \
  HostFError.c \
  HostFFlush.c \
  HostFGetC.c \
  HostFGetPos.c \
  HostFGetS.c \
  HostFOpen.c \
  HostFPrintF.c \
  HostFPutC.c \
  HostFPutS.c \
  HostFRead.c \
  HostFree.c \
  HostFReopen.c \
  HostFScanF.c \
  HostFSeek.c \
  HostFSetPos.c \
  HostFTell.c \
  HostFWrite.c \
  HostGestalt.c \
  HostGetDirectory.c \
  HostGetEnv.c \
  HostGetFileAttr.c \
  HostGetFile.c \
  HostGetHostID.c \
  HostGetHostPlatform.c \
  HostGetHostVersion.c \
  HostGetPreference.c \
  HostGMTime.c \
  HostGremlinCounter.c \
  HostGremlinIsRunning.c \
  HostGremlinLimit.c \
  HostGremlinNew.c \
  HostGremlinNumber.c \
  HostImportFile.c \
  HostImportFileWithID.c \
  HostIsCallingTrap.c \
  HostIsSelectorImplemented.c \
  HostLocalTime.c \
  HostLogFile.c \
  HostMalloc.c \
  HostMkDir.c \
  HostMkTime.c \
  HostOpenDir.c \
  HostProfileCleanup.c \
  HostProfileDetailFn.c \
  HostProfileDump.c \
  HostProfileGetCycles.c \
  HostProfileInit.c \
  HostProfileStart.c \
  HostProfileStop.c \
  HostPutFile.c \
  HostReadDir.c \
  HostRealloc.c \
  HostRemove.c \
  HostRename.c \
  HostRmDir.c \
  HostSaveScreen.c \
  HostSessionClose.c \
  HostSessionCreate.c \
  HostSessionOpen.c \
  HostSessionQuit.c \
  HostSessionSave.c \
  HostSetFileAttr.c \
  HostSetLogFileSize.c \
  HostSetPreference.c \
  HostSignalResume.c \
  HostSignalSend.c \
  HostSignalWait.c \
  HostSlotHasCard.c \
  HostSlotMax.c \
  HostSlotRoot.c \
  HostStat.c \
  HostStrFTime.c \
  HostTime.c \
  HostTmpFile.c \
  HostTmpNam.c \
  HostTraceClose.c \
  HostTraceInit.c \
  HostTraceOutputB.c \
  HostTraceOutputT.c \
  HostTraceOutputTL.c \
  HostTraceOutputVT.c \
  HostTraceOutputVTL.c \
  HostTruncate.c \
  HostUTime.c \
  INetLibCacheGetObject.c \
  INetLibCacheGetObjectV2.c \
  INetLibCacheList.c \
  INetLibCachePurge.c \
  INetLibCheckAntennaState.c \
  INetLibClose.c \
  INetLibConfigAliasGet.c \
  INetLibConfigAliasSet.c \
  INetLibConfigDelete.c \
  INetLibConfigIndexFromName.c \
  INetLibConfigList.c \
  INetLibConfigMakeActive.c \
  INetLibConfigRename.c \
  INetLibConfigSaveAs.c \
  INetLibCTPSend.c \
  INetLibGetEvent.c \
  INetLibIndexedCacheFind.c \
  INetLibOpen.c \
  INetLibPrepareCacheForHistory.c \
  INetLibSettingGet.c \
  INetLibSettingSet.c \
  INetLibSleep.c \
  INetLibSockClose.c \
  INetLibSockConnect.c \
  INetLibSockFileGetByIndex.c \
  INetLibSockHTTPAttrGet.c \
  INetLibSockHTTPAttrSet.c \
  INetLibSockHTTPReqCreate.c \
  INetLibSockHTTPReqSend.c \
  INetLibSockOpen.c \
  INetLibSockRead.c \
  INetLibSockSettingGet.c \
  INetLibSockSettingSet.c \
  INetLibSockStatus.c \
  INetLibSockWrite.c \
  INetLibURLCrack.c \
  INetLibURLGetInfo.c \
  INetLibURLOpen.c \
  INetLibURLsAdd.c \
  INetLibURLsCompare.c \
  INetLibWake.c \
  INetLibWiCmd.c \
  INetLibWirelessIndicatorCmd.c \
  InsPtCheckBlink.c \
  InsPtEnable.c \
  InsPtEnabled.c \
  InsPtGetHeight.c \
  InsPtGetLocation.c \
  InsPtInitialize.c \
  InsPtSetHeight.c \
  InsPtSetLocation.c \
  IntlGetRoutineAddress.c \
  IntlSetRoutineAddress.c \
  IrBind.c \
  IrClose.c \
  IrConnectIrLap.c \
  IrConnectReq.c \
  IrConnectRsp.c \
  IrDataReq.c \
  IrDisconnectIrLap.c \
  IrDiscoverReq.c \
  IrHandleEvent.c \
  IrIAS_Add.c \
  IrIAS_Next.c \
  IrIAS_Query.c \
  IrIAS_SetDeviceName.c \
  IrIsIrLapConnected.c \
  IrIsMediaBusy.c \
  IrIsNoProgress.c \
  IrIsRemoteBusy.c \
  IrLocalBusy.c \
  IrMaxRxSize.c \
  IrMaxTxSize.c \
  IrOpen.c \
  IrSetDeviceInfo.c \
  IrTestReq.c \
  IrUnbind.c \
  IrWaitForEvent.c \
  KbdDraw.c \
  KbdErase.c \
  KbdGetLayout.c \
  KbdGetPosition.c \
  KbdGetShiftState.c \
  KbdHandleEvent.c \
  KbdSetLayout.c \
  KbdSetPosition.c \
  KbdSetShiftState.c \
  KeyboardStatusFree.c \
  KeyboardStatusNew.c \
  KeyCurrentState.c \
  KeyRates.c \
  KeySetMask.c \
  LmGetLocaleSetting.c \
  LmGetNumLocales.c \
  LmLocaleToIndex.c \
  LocGetNumberSeparators.c \
  LstDrawList.c \
  LstEraseList.c \
  LstGetNumberOfItems.c \
  LstGetSelection.c \
  LstGetSelectionText.c \
  LstGetTopItem.c \
  LstGetVisibleItems.c \
  LstHandleEvent.c \
  LstMakeItemVisible.c \
  LstNewList.c \
  LstPopupList.c \
  LstScrollList.c \
  LstSetDrawFunction.c \
  LstSetHeight.c \
  LstSetListChoices.c \
  LstSetPosition.c \
  LstSetSelection.c \
  LstSetTopItem.c \
  MdmDial.c \
  MdmHangUp.c \
  MemCardFormat.c \
  MemCardInfo.c \
  MemChunkFree.c \
  MemChunkNew.c \
  MemCmp.c \
  MemDebugMode.c \
  MemHandleCardNo.c \
  MemHandleDataStorage.c \
  MemHandleFlags.c \
  MemHandleFree.c \
  MemHandleHeapID.c \
  MemHandleLock.c \
  MemHandleLockCount.c \
  MemHandleNew.c \
  MemHandleOwner.c \
  MemHandleResetLock.c \
  MemHandleResize.c \
  MemHandleSetOwner.c \
  MemHandleSize.c \
  MemHandleToLocalID.c \
  MemHandleUnlock.c \
  MemHeapCheck.c \
  MemHeapCompact.c \
  MemHeapDynamic.c \
  MemHeapFlags.c \
  MemHeapFreeByOwnerID.c \
  MemHeapFreeBytes.c \
  MemHeapID.c \
  MemHeapInit.c \
  MemHeapScramble.c \
  MemHeapSize.c \
  MemInit.c \
  MemInitHeapTable.c \
  MemKernelInit.c \
  MemLocalIDKind.c \
  MemLocalIDToGlobal.c \
  MemLocalIDToLockedPtr.c \
  MemLocalIDToPtr.c \
  MemMove.c \
  MemNumCards.c \
  MemNumHeaps.c \
  MemNumRAMHeaps.c \
  MemPtrCardNo.c \
  MemPtrDataStorage.c \
  MemPtrFlags.c \
  MemPtrHeapID.c \
  MemPtrNew.c \
  MemPtrOwner.c \
  MemPtrRecoverHandle.c \
  MemPtrResetLock.c \
  MemPtrResize.c \
  MemPtrSetOwner.c \
  MemPtrSize.c \
  MemPtrToLocalID.c \
  MemPtrUnlock.c \
  MemSemaphoreRelease.c \
  MemSemaphoreReserve.c \
  MemSet.c \
  MemSetDebugMode.c \
  MemStoreInfo.c \
  MemStoreSetInfo.c \
  MenuAddItem.c \
  MenuCmdBarAddButton.c \
  MenuCmdBarDisplay.c \
  MenuCmdBarGetButtonData.c \
  MenuDispose.c \
  MenuDrawMenu.c \
  MenuEraseStatus.c \
  MenuGetActiveMenu.c \
  MenuHandleEvent.c \
  MenuHideItem.c \
  MenuInit.c \
  MenuSetActiveMenu.c \
  MenuSetActiveMenuRscID.c \
  MenuShowItem.c \
  NetLibAddrAToIN.c \
  NetLibAddrINToA.c \
  NetLibBitGetFixed.c \
  NetLibBitGetUIntV.c \
  NetLibBitMove.c \
  NetLibBitPutFixed.c \
  NetLibBitPutUIntV.c \
  NetLibClose.c \
  NetLibConfigAliasGet.c \
  NetLibConfigAliasSet.c \
  NetLibConfigDelete.c \
  NetLibConfigIndexFromName.c \
  NetLibConfigList.c \
  NetLibConfigMakeActive.c \
  NetLibConfigRename.c \
  NetLibConfigSaveAs.c \
  NetLibConnectionRefresh.c \
  NetLibDmReceive.c \
  NetLibFinishCloseWait.c \
  NetLibGetHostByAddr.c \
  NetLibGetHostByName.c \
  NetLibGetServByName.c \
  NetLibHandlePowerOff.c \
  NetLibIFAttach.c \
  NetLibIFDetach.c \
  NetLibIFDown.c \
  NetLibIFGet.c \
  NetLibIFSettingGet.c \
  NetLibIFSettingSet.c \
  NetLibIFUp.c \
  NetLibMaster.c \
  NetLibOpen.c \
  NetLibOpenConfig.c \
  NetLibOpenCount.c \
  NetLibOpenIfCloseWait.c \
  NetLibReceive.c \
  NetLibReceivePB.c \
  NetLibSelect.c \
  NetLibSend.c \
  NetLibSendPB.c \
  NetLibSettingGet.c \
  NetLibSettingSet.c \
  NetLibSleep.c \
  NetLibSocketAccept.c \
  NetLibSocketAddr.c \
  NetLibSocketBind.c \
  NetLibSocketClose.c \
  NetLibSocketConnect.c \
  NetLibSocketListen.c \
  NetLibSocketOpen.c \
  NetLibSocketOptionGet.c \
  NetLibSocketOptionSet.c \
  NetLibSocketShutdown.c \
  NetLibTracePrintF.c \
  NetLibTracePutS.c \
  NetLibWake.c \
  OmGetCurrentLocale.c \
  OmGetIndexedLocale.c \
  OmGetNextSystemLocale.c \
  OmGetRoutineAddress.c \
  OmGetSystemLocale.c \
  OmLocaleToOverlayDBName.c \
  OmOverlayDBNameToLocale.c \
  OmSetSystemLocale.c \
  PceNativeCall.c \
  PdiDefineReaderDictionary.c \
  PdiDefineResizing.c \
  PdiDefineWriterDictionary.c \
  PdiEnterObject.c \
  PdiLibClose.c \
  PdiLibOpen.c \
  PdiReaderDelete.c \
  PdiReaderNew.c \
  PdiReadParameter.c \
  PdiReadProperty.c \
  PdiReadPropertyField.c \
  PdiReadPropertyName.c \
  PdiSetCharset.c \
  PdiSetEncoding.c \
  PdiWriteBeginObject.c \
  PdiWriteParameter.c \
  PdiWriteParameterStr.c \
  PdiWritePropertyBinaryValue.c \
  PdiWriteProperty.c \
  PdiWritePropertyFields.c \
  PdiWritePropertyStr.c \
  PdiWritePropertyValue.c \
  PdiWriterDelete.c \
  PdiWriterNew.c \
  PenCalibrate.c \
  PenClose.c \
  PenGetRawPen.c \
  PenOpen.c \
  PenRawToScreen.c \
  PenResetCalibration.c \
  PenScreenToRaw.c \
  PenSleep.c \
  PenWake.c \
  PhoneNumberLookup.c \
  PhoneNumberLookupCustom.c \
  PINGetInputAreaState.c \
  PINGetInputTriggerState.c \
  PINSetInputAreaState.c \
  PINSetInputTriggerState.c \
  PrefGetAppPreferences.c \
  PrefGetAppPreferencesV10.c \
  PrefGetPreference.c \
  PrefGetPreferences.c \
  PrefOpenPreferenceDB.c \
  PrefOpenPreferenceDBV10.c \
  PrefSetAppPreferences.c \
  PrefSetAppPreferencesV10.c \
  PrefSetPreference.c \
  PrefSetPreferences.c \
  PrgHandleEvent.c \
  PrgStartDialog.c \
  PrgStartDialogV31.c \
  PrgStopDialog.c \
  PrgUpdateDialog.c \
  PwdExists.c \
  PwdRemove.c \
  PwdSet.c \
  PwdVerify.c \
  RctCopyRectangle.c \
  RctGetIntersection.c \
  RctInsetRectangle.c \
  RctOffsetRectangle.c \
  RctPtInRectangle.c \
  RctSetRectangle.c \
  ResLoadConstant.c \
  ResLoadForm.c \
  ResLoadMenu.c \
  SclDrawScrollBar.c \
  SclGetScrollBar.c \
  SclHandleEvent.c \
  SclSetScrollBar.c \
  SecSelectViewStatus.c \
  SecVerifyPW.c \
  SelectDay.c \
  SelectDayV10.c \
  SelectOneTime.c \
  SelectTime.c \
  SelectTimeV33.c \
  SelectTimeZone.c \
  SerClearErr.c \
  SerClose.c \
  SerControl.c \
  SerGetSettings.c \
  SerGetStatus.c \
  SerialMgrInstall.c \
  SerOpen.c \
  SerPrimeWakeupHandler.c \
  SerReceive10.c \
  SerReceive.c \
  SerReceiveCheck.c \
  SerReceiveFlush.c \
  SerReceiveISP.c \
  SerReceiveWait.c \
  SerReceiveWindowClose.c \
  SerReceiveWindowOpen.c \
  SerSend10.c \
  SerSend.c \
  SerSendCheck.c \
  SerSendFlush.c \
  SerSendWait.c \
  SerSetReceiveBuffer.c \
  SerSetSettings.c \
  SerSetWakeupHandler.c \
  SerSleep.c \
  SerWake.c \
  SlkClose.c \
  SlkCloseSocket.c \
  SlkFlushSocket.c \
  SlkOpen.c \
  SlkOpenSocket.c \
  SlkProcessRPC.c \
  SlkReceivePacket.c \
  SlkSendPacket.c \
  SlkSetSocketListener.c \
  SlkSocketPortID.c \
  SlkSocketSetTimeout.c \
  SlkSysPktDefaultResponse.c \
  SlotCardGetSerialPort.c \
  SlotCardInfo.c \
  SlotCardIsFilesystemSupported.c \
  SlotCardLowLevelFormat.c \
  SlotCardMediaType.c \
  SlotCardMetrics.c \
  SlotCardPresent.c \
  SlotCardRelease.c \
  SlotCardReserve.c \
  SlotCardSectorRead.c \
  SlotCardSectorWrite.c \
  SlotClose.c \
  SlotCustomControl.c \
  SlotLibAPIVersion.c \
  SlotMediaType.c \
  SlotOpen.c \
  SlotPowerCheck.c \
  SlotSleep.c \
  SlotWake.c \
  SndCreateMidiList.c \
  SndDoCmd.c \
  SndGetDefaultVolume.c \
  SndInit.c \
  SndInterruptSmfIrregardless.c \
  SndPlayResource.c \
  SndPlaySmf.c \
  SndPlaySmfIrregardless.c \
  SndPlaySmfResource.c \
  SndPlaySmfResourceIrregardless.c \
  SndPlaySystemSound.c \
  SndSetDefaultVolume.c \
  SndStreamCreate.c \
  SndStreamCreateExtended.c \
  SndStreamDelete.c \
  SndStreamDeviceControl.c \
  SndStreamGetPan.c \
  SndStreamGetVolume.c \
  SndStreamPause.c \
  SndStreamSetPan.c \
  SndStreamSetVolume.c \
  SndStreamStart.c \
  SndStreamStop.c \
  SrmClearErr.c \
  SrmClose.c \
  SrmControl.c \
  SrmCustomControl.c \
  SrmExtOpenBackground.c \
  SrmExtOpen.c \
  SrmGetDeviceCount.c \
  SrmGetDeviceInfo.c \
  SrmGetStatus.c \
  SrmOpenBackground.c \
  SrmOpen.c \
  SrmPrimeWakeupHandler.c \
  SrmReceive.c \
  SrmReceiveCheck.c \
  SrmReceiveFlush.c \
  SrmReceiveWait.c \
  SrmReceiveWindowClose.c \
  SrmReceiveWindowOpen.c \
  SrmSend.c \
  SrmSendCheck.c \
  SrmSendFlush.c \
  SrmSendWait.c \
  SrmSetReceiveBuffer.c \
  SrmSetWakeupHandler.c \
  SrmSleep.c \
  SrmWake.c \
  SslClose.c \
  SslConsume.c \
  SslContextCreate.c \
  SslContextDestroy.c \
  SslContextGetLong.c \
  SslContextGetPtr.c \
  SslContextSetLong.c \
  SslContextSetPtr.c \
  SslFlush.c \
  SslLibClose.c \
  SslLibCreate.c \
  SslLibDestroy.c \
  SslLibGetLong.c \
  SslLibGetPtr.c \
  SslLibName.c \
  SslLibOpen.c \
  SslLibSetLong.c \
  SslLibSetPtr.c \
  SslLibSleep.c \
  SslLibWake.c \
  SslOpen.c \
  SslPeek.c \
  SslRead.c \
  SslReceive.c \
  SslSend.c \
  SslWrite.c \
  StatGetAttribute.c \
  StatHide.c \
  StatShow.c \
  StrAToI.c \
  StrCaselessCompare.c \
  StrCat.c \
  StrChr.c \
  StrCompareAscii.c \
  StrCompare.c \
  StrCopy.c \
  StrDelocalizeNumber.c \
  StrIToA.c \
  StrIToH.c \
  StrLen.c \
  StrLocalizeNumber.c \
  StrNCaselessCompare.c \
  StrNCat.c \
  StrNCompareAscii.c \
  StrNCompare.c \
  StrNCopy.c \
  StrPrintF.c \
  StrStr.c \
  StrToLower.c \
  StrVPrintF.c \
  SysAppExit.c \
  SysAppLaunch.c \
  SysAppLauncherDialog.c \
  SysAppStartup.c \
  SysBatteryDialog.c \
  SysBatteryInfo.c \
  SysBatteryInfoV20.c \
  SysBinarySearch.c \
  SysBroadcastActionCode.c \
  SysColdBoot.c \
  SysCopyStringResource.c \
  SysCreateDataBaseList.c \
  SysCreatePanelList.c \
  SysCurAppDatabase.c \
  SysDisableInts.c \
  SysDoze.c \
  SysErrString.c \
  SysEvGroupCreate.c \
  SysEvGroupRead.c \
  SysEvGroupSignal.c \
  SysEvGroupWait.c \
  SysFatalAlert.c \
  SysFatalAlertInit.c \
  SysFormPointerArrayToStrings.c \
  SysGetOrientation.c \
  SysGetOrientationTriggerState.c \
  SysGetOSVersionString.c \
  SysGetROMToken.c \
  SysGetStackInfo.c \
  SysGetTrapAddress.c \
  SysGraffitiReferenceDialog.c \
  SysHandleEvent.c \
  SysInit.c \
  SysInsertionSort.c \
  SysKernelInfo.c \
  SysKeyboardDialog.c \
  SysKeyboardDialogV10.c \
  SysLaunchConsole.c \
  SysLCDBrightness.c \
  SysLCDContrast.c \
  SysLibClose.c \
  SysLibFind.c \
  SysLibInstall.c \
  SysLibLoad.c \
  SysLibOpen.c \
  SysLibRemove.c \
  SysLibSleep.c \
  SysLibTblEntry.c \
  SysLibWake.c \
  SysMailboxCreate.c \
  SysMailboxDelete.c \
  SysMailboxFlush.c \
  SysMailboxSend.c \
  SysMailboxWait.c \
  SysNewOwnerID.c \
  SysNotifyBroadcast.c \
  SysNotifyBroadcastDeferred.c \
  SysNotifyBroadcastFromInterrupt.c \
  SysNotifyRegister.c \
  SysNotifyUnregister.c \
  SysQSort.c \
  SysRandom.c \
  SysReset.c \
  SysResSemaphoreCreate.c \
  SysResSemaphoreDelete.c \
  SysResSemaphoreRelease.c \
  SysResSemaphoreReserve.c \
  SysRestoreStatus.c \
  SysSemaphoreCreate.c \
  SysSemaphoreDelete.c \
  SysSemaphoreSet.c \
  SysSemaphoreSignal.c \
  SysSemaphoreWait.c \
  SysSetA5.c \
  SysSetAutoOffTime.c \
  SysSetOrientation.c \
  SysSetOrientationTriggerState.c \
  SysSetPerformance.c \
  SysSetTrapAddress.c \
  SysSleep.c \
  SysStringByIndex.c \
  SysTaskCreate.c \
  SysTaskDelay.c \
  SysTaskDelete.c \
  SysTaskID.c \
  SysTaskResume.c \
  SysTaskSetTermProc.c \
  SysTaskSuspend.c \
  SysTaskSwitching.c \
  SysTaskTrigger.c \
  SysTaskWait.c \
  SysTaskWaitClr.c \
  SysTaskWake.c \
  SysTicksPerSecond.c \
  SysTimerCreate.c \
  SysTimerDelete.c \
  SysTimerRead.c \
  SysTimerWrite.c \
  SysTranslateKernelErr.c \
  SysUIAppSwitch.c \
  SysUIBusy.c \
  SysUILaunch.c \
  SysUnimplemented.c \
  TblDrawTable.c \
  TblEditing.c \
  TblEraseTable.c \
  TblFindRowData.c \
  TblFindRowID.c \
  TblGetBounds.c \
  TblGetColumnSpacing.c \
  TblGetColumnWidth.c \
  TblGetCurrentField.c \
  TblGetItemBounds.c \
  TblGetItemFont.c \
  TblGetItemInt.c \
  TblGetItemPtr.c \
  TblGetLastUsableRow.c \
  TblGetNumberOfColumns.c \
  TblGetNumberOfRows.c \
  TblGetRowData.c \
  TblGetRowHeight.c \
  TblGetRowID.c \
  TblGetSelection.c \
  TblGetTopRow.c \
  TblGrabFocus.c \
  TblHandleEvent.c \
  TblHasScrollBar.c \
  TblInsertRow.c \
  TblMarkRowInvalid.c \
  TblMarkTableInvalid.c \
  TblRedrawTable.c \
  TblReleaseFocus.c \
  TblRemoveRow.c \
  TblRowInvalid.c \
  TblRowMasked.c \
  TblRowSelectable.c \
  TblRowUsable.c \
  TblSelectItem.c \
  TblSetBounds.c \
  TblSetColumnEditIndicator.c \
  TblSetColumnMasked.c \
  TblSetColumnSpacing.c \
  TblSetColumnUsable.c \
  TblSetColumnWidth.c \
  TblSetCustomDrawProcedure.c \
  TblSetItemFont.c \
  TblSetItemInt.c \
  TblSetItemPtr.c \
  TblSetItemStyle.c \
  TblSetLoadDataProcedure.c \
  TblSetRowData.c \
  TblSetRowHeight.c \
  TblSetRowID.c \
  TblSetRowMasked.c \
  TblSetRowSelectable.c \
  TblSetRowStaticHeight.c \
  TblSetRowUsable.c \
  TblSetSaveDataProcedure.c \
  TblSetSelection.c \
  TblUnhighlightSelection.c \
  TimAdjust.c \
  TimDateTimeToSeconds.c \
  TimeToAscii.c \
  TimeZoneToAscii.c \
  TimGetSeconds.c \
  TimGetTicks.c \
  TimInit.c \
  TimSecondsToDateTime.c \
  TimSetSeconds.c \
  TimTimeZoneToUTC.c \
  TimUTCToTimeZone.c \
  TsmGetFepMode.c \
  TsmSetFepMode.c \
  TxtByteAttr.c \
  TxtCaselessCompare.c \
  TxtCharAttr.c \
  TxtCharBounds.c \
  TxtCharEncoding.c \
  TxtCharIsValid.c \
  TxtCharSize.c \
  TxtCharWidth.c \
  TxtCharXAttr.c \
  TxtCompare.c \
  TxtConvertEncoding.c \
  TxtEncodingName.c \
  TxtFindString.c \
  TxtGetChar.c \
  TxtGetNextChar.c \
  TxtGetPreviousChar.c \
  TxtGetTruncationOffset.c \
  TxtGetWordWrapOffset.c \
  TxtMaxEncoding.c \
  TxtNameToEncoding.c \
  TxtParamString.c \
  TxtReplaceStr.c \
  TxtSetNextChar.c \
  TxtStrEncoding.c \
  TxtTransliterate.c \
  TxtWordBounds.c \
  UDAControl.c \
  UDAExchangeReaderNew.c \
  UDAExchangeWriterNew.c \
  UDAMemoryReaderNew.c \
  UIBrightnessAdjust.c \
  UIColorGetTableEntryIndex.c \
  UIColorGetTableEntryRGB.c \
  UIColorPopTable.c \
  UIColorPushTable.c \
  UIColorSetTableEntry.c \
  UIContrastAdjust.c \
  UIPickColor.c \
  VFSCustomControl.c \
  VFSDirCreate.c \
  VFSDirEntryEnumerate.c \
  VFSExportDatabaseToFile.c \
  VFSExportDatabaseToFileCustom.c \
  VFSFileClose.c \
  VFSFileCreate.c \
  VFSFileDBGetRecord.c \
  VFSFileDBGetResource.c \
  VFSFileDBInfo.c \
  VFSFileDelete.c \
  VFSFileEOF.c \
  VFSFileGetAttributes.c \
  VFSFileGetDate.c \
  VFSFileOpen.c \
  VFSFileRead.c \
  VFSFileReadData.c \
  VFSFileRename.c \
  VFSFileResize.c \
  VFSFileSeek.c \
  VFSFileSetAttributes.c \
  VFSFileSetDate.c \
  VFSFileSize.c \
  VFSFileTell.c \
  VFSFileWrite.c \
  VFSGetDefaultDirectory.c \
  VFSImportDatabaseFromFile.c \
  VFSImportDatabaseFromFileCustom.c \
  VFSInit.c \
  VFSInstallFSLib.c \
  VFSRegisterDefaultDirectory.c \
  VFSRemoveFSLib.c \
  VFSUnregisterDefaultDirectory.c \
  VFSVolumeEnumerate.c \
  VFSVolumeFormat.c \
  VFSVolumeGetLabel.c \
  VFSVolumeInfo.c \
  VFSVolumeMount.c \
  VFSVolumeSetLabel.c \
  VFSVolumeSize.c \
  VFSVolumeUnmount.c \
  WinAddWindow.c \
  WinClipRectangle.c \
  WinCopyRectangle.c \
  WinCreateBitmapWindow.c \
  WinCreateOffscreenWindow.c \
  WinCreateWindow.c \
  WinDeleteWindow.c \
  WinDisableWindow.c \
  WinDisplayToWindowPt.c \
  WinDrawBitmap.c \
  WinDrawChar.c \
  WinDrawChars.c \
  WinDrawGrayLine.c \
  WinDrawGrayRectangleFrame.c \
  WinDrawInvertedChars.c \
  WinDrawLine.c \
  WinDrawPixel.c \
  WinDrawRectangle.c \
  WinDrawRectangleFrame.c \
  WinDrawTruncChars.c \
  WinDrawWindowFrame.c \
  WinEnableWindow.c \
  WinEraseChars.c \
  WinEraseLine.c \
  WinErasePixel.c \
  WinEraseRectangle.c \
  WinEraseRectangleFrame.c \
  WinEraseWindow.c \
  WinFillLine.c \
  WinFillRectangle.c \
  WinGetActiveWindow.c \
  WinGetBitmap.c \
  WinGetBounds.c \
  WinGetClip.c \
  WinGetCoordinateSystem.c \
  WinGetDisplayExtent.c \
  WinGetDisplayWindow.c \
  WinGetDrawWindowBounds.c \
  WinGetDrawWindow.c \
  WinGetFirstWindow.c \
  WinGetFramesRectangle.c \
  WinGetPattern.c \
  WinGetPatternType.c \
  WinGetPixel.c \
  WinGetPixelRGB.c \
  WinGetScalingMode.c \
  WinGetSupportedDensity.c \
  WinGetWindowExtent.c \
  WinGetWindowFrameRect.c \
  WinIndexToRGB.c \
  WinInitializeWindow.c \
  WinInvertChars.c \
  WinInvertLine.c \
  WinInvertPixel.c \
  WinInvertRectangle.c \
  WinInvertRectangleFrame.c \
  WinModal.c \
  WinMoveWindowAddr.c \
  WinPaintBitmap.c \
  WinPaintChar.c \
  WinPaintChars.c \
  WinPaintLine.c \
  WinPaintLines.c \
  WinPaintPixel.c \
  WinPaintPixels.c \
  WinPaintRectangle.c \
  WinPaintRectangleFrame.c \
  WinPaintRoundedRectangleFrame.c \
  WinPaintTiledBitmap.c \
  WinPalette.c \
  WinPopDrawState.c \
  WinPushDrawState.c \
  WinRemoveWindow.c \
  WinResetClip.c \
  WinRestoreBits.c \
  WinRGBToIndex.c \
  WinSaveBits.c \
  WinScaleCoord.c \
  WinScalePoint.c \
  WinScaleRectangle.c \
  WinScreenGetAttribute.c \
  WinScreenInit.c \
  WinScreenLock.c \
  WinScreenMode.c \
  WinScreenUnlock.c \
  WinScrollRectangle.c \
  WinSetActiveWindow.c \
  WinSetBackColor.c \
  WinSetBackColorRGB.c \
  WinSetBounds.c \
  WinSetClip.c \
  WinSetColors.c \
  WinSetConstraintsSize.c \
  WinSetCoordinateSystem.c \
  WinSetDrawMode.c \
  WinSetDrawWindow.c \
  WinSetForeColor.c \
  WinSetForeColorRGB.c \
  WinSetPattern.c \
  WinSetPatternType.c \
  WinSetScalingMode.c \
  WinSetTextColor.c \
  WinSetTextColorRGB.c \
  WinSetUnderlineMode.c \
  WinUnscaleCoord.c \
  WinUnscalePoint.c \
  WinUnscaleRectangle.c \
  WinValidateHandle.c \
  WinWindowToDisplayPt.c

awk '
/^#/ {
  next;
} 
{
  filename = $5 ".c";
  print "#include <PalmOS.h>" >> filename;
  print "#include <PalmCompatibility.h>" >> filename;
  print "#include <VFSMgr.h>" >> filename;
  print "#include <ExpansionMgr.h>" >> filename;
  print "#include <DLServer.h>" >> filename;
  print "#include <SerialMgrOld.h>" >> filename;
  print "#include <UDAMgr.h>" >> filename;
  print "#include <PceNativeCall.h>" >> filename;
  print "#include <FixedMath.h>" >> filename;
  print "#include <CPMLib.h>" >> filename;
  print "#include <GPSLib68K.h>" >> filename;
  print "#include <GPDLib.h>" >> filename;
  print "#include <PdiLib.h>" >> filename;
  print "#include <BtLib.h>" >> filename;
  print "#include <FSLib.h>" >> filename;
  print "#include <SslLib.h>" >> filename;
  print "#include <INetMgr.h>" >> filename;
  print "#include <SlotDrvrLib.h>" >> filename;
  print "" >> filename;

  rtype = $4;
  gsub("_", " ", rtype);
  s = rtype;
  if (!(rtype ~ /[*]$/)) {
    s = s " ";
  }
  s = s $5 "(";
  nargs = 0 + $6;
  varargs = 0;
  lastarg = "";
  if (nargs == 0) {
    s = s "void";
  } else {
    for (i = 0; i < nargs; i++) {
      if (i > 0) s = s ", ";
      atype = $(7 + i*2);
      if (atype != "sys_va_list") {
        gsub("_", " ", atype);
      }
      s = s atype;
      if (atype == "...") {
        varargs = 1;
        break;
      }
      if (!(atype ~ /[*]$/)) {
        s = s " ";
      }
      lastarg = $(7 + i*2 + 1);
      s = s lastarg;
    }
  }
  s = s ") {";
  print s >> filename;
  if ($1 ~ /LIB$/) lib = $1; else lib = "0";
  if ($1 == "SYS_TRAP") sel = 0; else sel = $3;

  if (varargs == 1) {
    print "  sys_va_list ap;" >> filename;
    print "  sys_va_start(ap, " lastarg ");" >> filename;
  }

  if (rtype ~ /[*]$/ || rtype == "MemHandle" || rtype == "MemPtr" || rtype == "WinHandle" || rtype == "DmOpenRef" || rtype == "FileHand") {
    print "  void *pret;" >> filename;
    s = "  pumpkin_system_call_p(" lib ", " $2 ", " sel ", NULL, &pret";
    if (nargs > 0) {
      for (i = 0; i < nargs; i++) {
        arg = $(7 + i*2 + 1);
        pos = index(arg, "[");
        if (pos > 0) arg = substr(arg, 1, pos-1);
        s = s ", " arg;
      }
    }
    s = s ");";
    print s >> filename;
    if (varargs == 1) {
      print "  sys_va_end(ap);" >> filename;
    }
    print "  return (" rtype ")pret;" >> filename;
  } else {
    if (rtype != "void") {
      print "  uint64_t iret;" >> filename;
      s = "  pumpkin_system_call_p(" lib ", " $2 ", " sel ", &iret, NULL";
    } else {
      s = "  pumpkin_system_call_p(" lib ", " $2 ", " sel ", NULL, NULL";
    }
    if (nargs > 0) {
      for (i = 0; i < nargs; i++) {
        arg = $(7 + i*2 + 1);
        pos = index(arg, "[");
        if (pos > 0) arg = substr(arg, 1, pos-1);
        s = s ", " arg;
      }
    }
    s = s ");";
    print s >> filename;
    if (varargs == 1) {
      print "  sys_va_end(ap);" >> filename;
    }
    if (rtype != "void") {
      print "  return (" rtype ")iret;" >> filename;
    }
  }
  print "}" >> filename;
  close(filename);
}
' ../libpumpkin/traps.txt

exit 0
