/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define if building armlets */
/* #undef BUILD_ARMLETS */

/* Define to enable gesture debug indicator */
/* #undef ENABLE_GESTURE_DEBUG */

/* Define if scroll should stop when reaching bottom of page */
#define ENABLE_SCROLL_TO_BOTTOM 

/* Define if using axxpac support */
/* #undef HAVE_AXXPAC */

/* Define if using FiveWay SDK */
/* #undef HAVE_FIVEWAY_SDK */

/* Define if using anti-aliased fonts */
//#define HAVE_GRAY_FONT 

/* Define if using Handera SDK */
/* #undef HAVE_HANDERA_SDK */

/* Define if using Handspring SDK */
/* #undef HAVE_HANDSPRING_SDK */

/* Define if using hires */
#define HAVE_HIRES 

/* Define if using i-mode support */
/* #undef HAVE_IMODE */

/* Define to 1 if you have the <inttypes.h> header file. */
/* #undef HAVE_INTTYPES_H */

/* Define if using jogdial */
/* #undef HAVE_JOGDIAL */

/* Define to 1 if you have the <memory.h> header file. */
/* #undef HAVE_MEMORY_H */

/* Define to 1 if you have the <PalmChars.h> header file. */
/* #undef HAVE_PALMCHARS_H */

/* Define if using PalmCUnit */
/* #undef HAVE_PALMCUNIT */

/* Define if using Palm DIA */
#define HAVE_PALM_DIA 

/* Define if pilrc supports extended bitmaps */
#define HAVE_PILRC_EXBMP 

/* Define if using rotate */
#define HAVE_ROTATE 

/* Define if using silkscreen */
#define HAVE_SILKSCREEN 

/* Define if using Sony Silkscreen SDK */
/* #undef HAVE_SONYSILK_SDK */

/* Define to 1 if you have the <SonySlkw.h> header file. */
/* #undef HAVE_SONYSLKW_H */

/* Define if using Sony SDK */
/* #undef HAVE_SONY_SDK */

/* Define to 1 if you have the <stdint.h> header file. */
/* #undef HAVE_STDINT_H */

/* Define to 1 if you have the <stdlib.h> header file. */
/* #undef HAVE_STDLIB_H */

/* Define to 1 if you have the <strings.h> header file. */
/* #undef HAVE_STRINGS_H */

/* Define to 1 if you have the <string.h> header file. */
/* #undef HAVE_STRING_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
/* #undef HAVE_SYS_STAT_H */

/* Define to 1 if you have the <sys/types.h> header file. */
/* #undef HAVE_SYS_TYPES_H */

/* Define to 1 if you have the <unistd.h> header file. */
/* #undef HAVE_UNISTD_H */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define if supporting skins */
/* #undef RETURN_TO_PREV_APP */

/* Define to 1 if you have the ANSI C header files. */
/* #undef STDC_HEADERS */

/* Define if supporting PPI */
/* #undef SUPPORT_PPI */

/* Define if supporting skins */
/* #undef SUPPORT_SKINS */

/* Define if supporting search transliteration */
#define SUPPORT_TRANSLITERATION 

/* Define if using VFS fonts */
#define SUPPORT_VFS_FONTS 

/* Define if supporting word lookup */
/* #undef SUPPORT_WORD_LOOKUP */
