PumpkinDisplay.jar: PumpkinDisplay.class
	jar cfe PumpkinDisplay.jar PumpkinDisplay *.class

PumpkinDisplay.class: PumpkinDisplay.java
	javac PumpkinDisplay.java

clean:
	rm -f PumpkinDisplay.jar *.class
