Err MapInit(Boolean highDensity, RectangleType *rect, DmOpenRef ptRef, WinHandle whBuf);
Err MapSetData(DmOpenRef dataRef);
void MapSetCurrentLog(FileHand f);
void MapSetStoredLog(FileHand f);
void MapFinish(void);
void MapDraw(void);
void MapDrawRel(WinHandle src, WinHandle dst, Int16 dx, Int16 dy);
void MapColor(Int16 positionColor, Int16 currentColor, Int16 storedColor, Int16 selectedColor, Int16 targetColor);
void MapFont(FontID font);
void MapCoord(double lat, double lon, double dlat, double dlon);
void MapCenter(double lat, double lon);
void MapCenterXY(UInt16 x, UInt16 y);
void MapGetCenter(double *lat, double *lon);
void MapMoveXY(Int16 dx, Int16 dy);
void MapZoom(double dlat, double dlon);
void MapZoomOffset(Int16 offset);
void MapZoomLevel(Int16 level);
void MapPosition(double lat, double lon, double speed, double course);
void MapLock(Boolean locked);
void MapSetTarget(double lat, double lon);
void MapResetTarget(void);
void MapDrawScale(double d, Int16 sx, Int16 sy);
void MapInvalid(void);
Boolean MapWaypointDistance(WaypointType *p, float *d);
void MapFindReset(void);
void MapSetRoute(Int16 order, char *name);
void MapStartMeasure(Int16);
void MapStopMeasure(void);
void MapMeasurePoint(UInt16 x0, UInt16 y0, UInt16 x1, UInt16 y1);
void MapMeasureAddPoint(UInt16 x, UInt16 y);
