Err SymbolInit(Boolean highDensity);
void SymbolFinish(void);
UInt16 GetSymbolCount(void);
UInt16 GetSymbolIndex(UInt16 symbol);
UInt16 GetSymbolType(UInt16 symbol);
UInt16 GetSymbolCategory(UInt16 i);
char *GetSymbolName(UInt16 symbol);
void DrawSymbolTable(RectangleType *bounds, Int16 first);
Int16 SelectSymbol(Int16 ex, Int16 ey, Int16 first);
void DrawSymbol(UInt16 id, Int16 x, Int16 y, Boolean centered, char *name, FontID font, UInt16 color, Boolean now);
UInt16 GetSelectedSymbol(void);
void SetSelectedSymbol(UInt16);
