//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 18:56:46  on quinta-feira, 2 de maio de 2024
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Untitled"
//
//	Palm App Version:		"1.0"


//	Resource: PICT 3900
#define VisitedSystemBitmap                       3900

//	Resource: PICT 4500
#define WormholeBitmap                            4500

//	Resource: PICT 3500
#define CurrentSystemBitmap                       3500

//	Resource: PICT 3300
#define SystemBitmap                              3300

//	Resource: PICT 3700
#define ShortRangeSystemBitmap                    3700

//	Resource: PICT 4100
#define CurrentVisitedSystemBitmap                4100

//	Resource: PICT 4300
#define VisitedShortRangeSystemBitmap             4300

//	Resource: PICT 4700
#define SmallWormholeBitmap                       4700

//	Resource: PICT 5300
#define FleaBitmap                                5300

//	Resource: PICT 5500
#define FleaDamagedBitmap                         5500

//	Resource: PICT 6100
#define GnatBitmap                                6100

//	Resource: PICT 6300
#define GnatDamagedBitmap                         6300

//	Resource: PICT 6900
#define FireflyBitmap                             6900

//	Resource: PICT 7100
#define FireflyDamagedBitmap                      7100

//	Resource: PICT 7300
#define FireflyShieldedBitmap                     7300

//	Resource: PICT 7500
#define FireflyShDamBitmap                        7500

//	Resource: PICT 7700
#define MosquitoBitmap                            7700

//	Resource: PICT 7900
#define MosquitoDamagedBitmap                     7900

//	Resource: PICT 8100
#define MosquitoShieldedBitmap                    8100

//	Resource: PICT 8300
#define MosquitoShDamBitmap                       8300

//	Resource: PICT 8500
#define BumblebeeBitmap                           8500

//	Resource: PICT 8700
#define BumblebeeDamagedBitmap                    8700

//	Resource: PICT 8900
#define BumblebeeShieldedBitmap                   8900

//	Resource: PICT 9100
#define BumblebeeShDamBitmap                      9100

//	Resource: PICT 9300
#define BeetleBitmap                              9300

//	Resource: PICT 9500
#define BeetleDamagedBitmap                       9500

//	Resource: PICT 9700
#define BeetleShieldedBitmap                      9700

//	Resource: PICT 9900
#define BeetleShDamBitmap                         9900

//	Resource: PICT 10100
#define HornetBitmap                              10100

//	Resource: PICT 10300
#define HornetDamagedBitmap                       10300

//	Resource: PICT 10500
#define HornetShieldedBitmap                      10500

//	Resource: PICT 10700
#define HornetShDamBitmap                         10700

//	Resource: PICT 10900
#define GrasshopperBitmap                         10900

//	Resource: PICT 11100
#define GrasshopperDamagedBitmap                  11100

//	Resource: PICT 11300
#define GrasshopperShieldedBitmap                 11300

//	Resource: PICT 11500
#define GrasshopperShDamBitmap                    11500

//	Resource: PICT 11700
#define TermiteBitmap                             11700

//	Resource: PICT 11900
#define TermiteDamagedBitmap                      11900

//	Resource: PICT 12100
#define TermiteShieldedBitmap                     12100

//	Resource: PICT 12300
#define TermiteShDamBitmap                        12300

//	Resource: PICT 12500
#define WaspBitmap                                12500

//	Resource: PICT 12700
#define WaspDamagedBitmap                         12700

//	Resource: PICT 12900
#define WaspShieldedBitmap                        12900

//	Resource: PICT 13100
#define WaspShDamBitmap                           13100

//	Resource: PICT 13300
#define MonsterBitmap                             13300

//	Resource: PICT 13500
#define MonsterDamagedBitmap                      13500

//	Resource: PICT 14100
#define DragonflyBitmap                           14100

//	Resource: PICT 14300
#define DragonflyDamagedBitmap                    14300

//	Resource: PICT 14500
#define DragonflyShieldedBitmap                   14500

//	Resource: PICT 14700
#define DragonflyShDamBitmap                      14700

//	Resource: PICT 14900
#define MantisBitmap                              14900

//	Resource: PICT 15100
#define MantisDamagedBitmap                       15100

//	Resource: PICT 15300
#define MantisShieldedBitmap                      15300

//	Resource: PICT 15500
#define MantisShDamBitmap                         15500

//	Resource: PICT 16500
#define RetireBitmap                              16500

//	Resource: PICT 16700
#define DestroyedBitmap                           16700

//	Resource: PICT 5100
#define UtopiaBitmap                              5100

//	Resource: PICT 4900
#define SpaceTraderBitmap                         4900

//	Resource: PICT 16900
#define PirateBitmap                              16900

//	Resource: PICT 17100
#define PoliceBitmap                              17100

//	Resource: PICT 17300
#define TraderBitmap                              17300

//	Resource: PICT 17500
#define AlienBitmap                               17500

//	Resource: PICT 17700
#define AttackBitmap                              17700

//	Resource: PICT 17900
#define Attack2Bitmap                             17900

//	Resource: PICT 15700
#define ScarabBitmap                              15700

//	Resource: PICT 18100
#define SpecialBitmap                             18100

//	Resource: PICT 15900
#define BottleBitmap                              15900

//	Resource: PICT 16100
#define ScarabDamagedBitmap                       16100

//	Resource: PICT 18200
#define AboutBitmap                               18200


//	Resource: tbmf 7900
#define BottleDamagedBitmapFamily                 7900

//	Resource: tbmf 7800
#define BottleBitmapFamily                        7800

//	Resource: tbmf 11100
#define Attack2BitmapFamily                       11100

//	Resource: tbmf 9500
#define PirateBitmapFamily                        9500

//	Resource: tbmf 9600
#define PoliceBitmapFamily                        9600

//	Resource: tbmf 9800
#define AlienBitmapFamily                         9800

//	Resource: tbmf 9700
#define TraderBitmapFamily                        9700

//	Resource: tbmf 11000
#define AttackBitmapFamily                        11000

//	Resource: tbmf 9900
#define SpecialBitmapFamily                       9900

//	Resource: tbmf 7400
#define ScarabBitmapFamily                        7400

//	Resource: tbmf 7500
#define ScarabDamagedBitmapFamily                 7500

//	Resource: tbmf 12000
#define DestroyedBitmapFamily                     12000

//	Resource: tbmf 7300
#define MantisShDamBitmapFamily                   7300

//	Resource: tbmf 7200
#define MantisShieldedBitmapFamily                7200

//	Resource: tbmf 7100
#define MantisDamagedBitmapFamily                 7100

//	Resource: tbmf 7000
#define MantisBitmapFamily                        7000

//	Resource: tbmf 6900
#define DragonflyShDamBitmapFamily                6900

//	Resource: tbmf 6800
#define DragonflyShieldedBitmapFamily             6800

//	Resource: tbmf 6700
#define DragonflyDamagedBitmapFamily              6700

//	Resource: tbmf 6600
#define DragonflyBitmapFamily                     6600

//	Resource: tbmf 6300
#define MonsterDamagedBitmapFamily                6300

//	Resource: tbmf 6200
#define MonsterBitmapFamily                       6200

//	Resource: tbmf 6100
#define WaspShDamBitmapFamily                     6100

//	Resource: tbmf 6000
#define WaspShieldedBitmapFamily                  6000

//	Resource: tbmf 5900
#define WaspDamagedBitmapFamily                   5900

//	Resource: tbmf 5800
#define WaspBitmapFamily                          5800

//	Resource: tbmf 5700
#define TermiteShDamBitmapFamily                  5700

//	Resource: tbmf 5600
#define TermiteShieldedBitmapFamily               5600

//	Resource: tbmf 5500
#define TermiteDamagedBitmapFamily                5500

//	Resource: tbmf 5400
#define TermiteBitmapFamily                       5400

//	Resource: tbmf 5300
#define GrasshopperShDamBitmapFamily              5300

//	Resource: tbmf 5200
#define GrasshopperShieldedBitmapFamily           5200

//	Resource: tbmf 5100
#define GrasshopperDamagedBitmapFamily            5100

//	Resource: tbmf 5000
#define GrasshopperBitmapFamily                   5000

//	Resource: tbmf 4900
#define HornetShDamBitmapFamily                   4900

//	Resource: tbmf 4800
#define HornetShieldedBitmapFamily                4800

//	Resource: tbmf 4700
#define HornetDamagedBitmapFamily                 4700

//	Resource: tbmf 4600
#define HornetBitmapFamily                        4600

//	Resource: tbmf 4500
#define BeetleShDamBitmapFamily                   4500

//	Resource: tbmf 4400
#define BeetleShieldedBitmapFamily                4400

//	Resource: tbmf 4300
#define BeetleDamagedBitmapFamily                 4300

//	Resource: tbmf 4200
#define BeetleBitmapFamily                        4200

//	Resource: tbmf 4100
#define BumblebeeShDamBitmapFamily                4100

//	Resource: tbmf 4000
#define BumblebeeShieldedBitmapFamily             4000

//	Resource: tbmf 3900
#define BumblebeeDamagedBitmapFamily              3900

//	Resource: tbmf 3800
#define BumblebeeBitmapFamily                     3800

//	Resource: tbmf 3700
#define MosquitoShDamBitmapFamily                 3700

//	Resource: tbmf 3600
#define MosquitoShieldedBitmapFamily              3600

//	Resource: tbmf 3500
#define MosquitoDamagedBitmapFamily               3500

//	Resource: tbmf 3400
#define MosquitoBitmapFamily                      3400

//	Resource: tbmf 3300
#define FireflyShDamBitmapFamily                  3300

//	Resource: tbmf 3200
#define FireflyShieldedBitmapFamily               3200

//	Resource: tbmf 3100
#define FireflyDamagedBitmapFamily                3100

//	Resource: tbmf 3000
#define FireflyBitmapFamily                       3000

//	Resource: tbmf 2700
#define GnatDamagedBitmapFamily                   2700

//	Resource: tbmf 2600
#define GnatBitmapFamily                          2600

//	Resource: tbmf 1100
#define RetireBitmapFamily                        1100

//	Resource: tbmf 2300
#define FleaDamagedBitmapFamily                   2300

//	Resource: tbmf 2200
#define FleaBitmapFamily                          2200

//	Resource: tbmf 1800
#define UtopiaBitmapFamily                        1800

//	Resource: tbmf 1500
#define SpaceTraderBitmapFamily                   1500

//	Resource: tbmf 1700
#define SmallWormholeBitmapFamily                 1700

//	Resource: tbmf 1600
#define WormholeBitmapFamily                      1600

//	Resource: tbmf 2100
#define VisitedShortRangeSystemBitmapFamily       2100

//	Resource: tbmf 2000
#define CurrentVisitedSystemBitmapFamily          2000

//	Resource: tbmf 1900
#define VisitedSystemBitmapFamily                 1900

//	Resource: tbmf 1400
#define ShortRangeSystemBitmapFamily              1400

//	Resource: tbmf 1300
#define CurrentSystemBitmapFamily                 1300

//	Resource: tbmf 1200
#define SystemBitmapFamily                        1200

//	Resource: tbmf 1000
#define AboutBitmapFamily                         1000

