PROGRAM=libchipmunk
SOURCE=chipmunk.c cpArbiter.c cpArray.c cpBBTree.c cpBody.c cpCollision.c cpConstraint.c cpDampedRotarySpring.c cpDampedSpring.c \
       cpGearJoint.c cpGrooveJoint.c cpHashSet.c cpHastySpace.c cpMarch.c cpPinJoint.c cpPivotJoint.c cpPolyShape.c cpPolyline.c \
       cpRatchetJoint.c cpRobust.c cpRotaryLimitJoint.c cpShape.c cpSimpleMotor.c cpSlideJoint.c cpSpace.c cpSpaceComponent.c \
       cpSpaceDebug.c cpSpaceHash.c cpSpaceQuery.c cpSpaceStep.c cpSpatialIndex.c cpSweep1D.c
CUSTOMFLAGS=-I. -DNDEBUG

include ../common.mak
include ../lib.mak
