PROGRAM=DateBook
SOURCE=DateAgenda.c DateAlarm.c Datebook.c DateDay.c DateDB.c DateDisplay.c DateGlobals.c DateMonth.c DatePref.c DateTransfer.c DateWeek.c ToDoDB.c
APPNAME=Date Book
APPID=date

include ../common.mak
include ../commonp.mak
include ../app.mak
