PROGRAM=libzycore
SOURCE=Allocator.c ArgParse.c Bitset.c Format.c List.c Memory.c Process.c String.c Synchronization.c Terminal.c Thread.c Vector.c Zycore.c
CUSTOMFLAGS=-I.

include ../common.mak
include ../lib.mak
