PROGRAM=libpluto
SOURCE=VectorGraphics.c plutosvg.c plutovg-blend.c plutovg-dash.c plutovg-font.c plutovg-geometry.c plutovg-paint.c \
       plutovg-rle.c plutovg.c sw_ft_math.c sw_ft_raster.c sw_ft_stroker.c
CUSTOMPFLAGS=-I.

include ../common.mak
include ../commonp.mak
include ../lib.mak
