include ../common.mak

PROGRAM=libzydis
SOURCE=MetaInfo.c Mnemonic.c Register.c Segment.c SharedData.c String.c Utils.c Zydis.c Decoder.c DecoderData.c Encoder.c EncoderData.c Disassembler.c Formatter.c FormatterBuffer.c FormatterATT.c FormatterBase.c FormatterIntel.c
CUSTOMFLAGS=-I. -I$(SRC)/libzycore
LIBS=-lzycore

include ../lib.mak
