SOURCE=hotsync.c userland.c \
       cmp.c debug.c dlp.c \
       inet.c md5.c net.c padp.c pi-buffer.c pi-file.c serial.c \
       slp.c socket.c sys.c syspkt.c threadsafe.c srmserial.c unixserial.c utils.c
CUSTOMPFLAGS=-I. -DHAVE_CONFIG_H
RCP=resource.rcp
RCPDEP=hotsync.bmp
APPNAME=Hotsync
APPID=Hots

include ../common.mak
include ../commonp.mak
include ../app.mak
