SOURCE=forc.c lexer.c parser.c ht.c type.c buffer.c section.c findargs.o assembler.c linker.o heap.o run.o
RCP=resource.rcp
APPNAME=forc
APPID=fORc

include ../common.mak
include ../commonp.mak
include ../app.mak
