# additional package(s) to install (example for Ubuntu):
# sudo apt install libpipewire-0.3-dev libspa-0.2-dev

PROGRAM=libapipewire
SOURCE=libapipewire.c
CUSTOMFLAGS=-I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2
LIBS=-lpipewire-0.3

include ../common.mak
include ../lib.mak
