# additional package(s) to install (example for Ubuntu):
# sudo apt install libxcb1-dev libxcb-ewmh-dev libxcb-image0-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev

PROGRAM=libwxcb
SOURCE=libwxcb.c
LIBS=-lxcb -lxcb-image -lxkbcommon -lxkbcommon-x11 -lxcb-xkb -lxcb-ewmh

include ../common.mak
include ../lib.mak
